name: Build Demo App

on: [push, workflow_dispatch]

jobs:
  run-tests:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v1

      - name: Run Tests
        run: |
          cd Demo\ App
          cp .env.example .env
          xcodebuild -scheme Twift_SwiftUI
