name: Docs Coverage Comment

on: [push, pull_request]

jobs:
  report-coverage:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install swift-doc
        run: brew install swiftdocorg/formulae/swift-doc

      - name: Generate coverage report
        id: coverageReport
        run: |
          body="$(swift-doc coverage "./Sources" --minimum-access-level public | sed '/^$/q' | head -n 1000)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"
          echo $body
          
      - name: Comment on commit
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Documentation coverage after this commit:
            
            ```
            ${{steps.coverage-report.outputs.body}}
            ```
