name: Documentation Coverage Report

on: [push, workflow_dispatch]

jobs:
  coverage-report:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install swift-doc
        run: |
          brew install swiftdocorg/formulae/swift-doc

      - id: report
        name: Run `swift-doc coverage`
        run: |
          swift-doc coverage Sources --output report.json
          content=`cat ./report.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=report::$content"

      - name: Checkout `badges` branch
        run: |
          git checkout badges
          
      - id: coverage
        name: Round coverage percentage
        env:
          coverage_percent: ${{fromJson(steps.report.outputs.report).data.totals.percent}}
        run: |
          percent=`printf "%.0f" "$coverage_percent"`
          echo "::set-output name=coverage::$percent"

      - name: Good coverage badge
        if: steps.coverage.outputs.coverage >= 80
        uses: emibcn/badge-action@v1.2.1
        with:
          label: 'Docs Coverage'
          status: '${{steps.coverage.outputs.coverage}}%'
          color: '34c759'
          path: '.github/badges/coverage.svg'
          
      - name: Okay coverage badge
        if: steps.coverage.outputs.coverage >= 50
        uses: emibcn/badge-action@v1.2.1
        with:
          label: 'Docs Coverage'
          status: '${{steps.coverage.outputs.coverage}}%'
          color: 'f59500'
          path: '.github/badges/coverage.svg'

      - name: Poor coverage badge
        if: steps.coverage.outputs.coverage < 50
        uses: emibcn/badge-action@v1.2.1
        with:
          label: 'Docs Coverage'
          status: '${{steps.coverage.outputs.coverage}}%'
          color: 'ff3b30'
          path: '.github/badges/coverage.svg'
          
      - name: Commit badge
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ".github/badges/coverage.svg"
          git commit -m "Add/Update badge"
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          branch: badges
