name: Documentation Coverage Report

on: [push, workflow_dispatch]

jobs:
  coverage-report:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install swift-doc
        run: |
          brew install swiftdocorg/formulae/swift-doc

      - id: report
        name: Run `swift-doc coverage`
        run: |
          swift-doc coverage Sources --output report.json
          content=`cat ./report.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=report::$content"

      - name: Generate badge
        uses: emibcn/badge-action@v1.2.1
        with:
          label: 'Doc Coverage'
          status: '${{fromJson(steps.report.outputs.report).count}}/${{fromJson(steps.report.outputs.report).documented}}'
          color: 'blue'
          path: '.github/badges/coverage.svg'
          
      - name: Commit badge
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ".github/badges/coverage.svg"
          git commit -m "Add/Update badge"
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          branch: badges
